---

- name: "copy artifacts to server"
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: .

- name: "extract file"
  become: true
  shell: |
    tar xzvf artifact.tar.gz

- name: "Start node server"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start